### ISSUE TITLE
romanisim 0.5.2 and numpy 2.1.1

### ISSUE THREAD

**Issue by qnov** [spacetelescope/romanisim#148]
Hello,

is the current romanisim version (0.5.2) expected to be compatible with numpy 2.1.1? 

my problem is that I could install romanisim but then when I tried to run it I got the following  error message 

%%%%%%%%
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.
%%%%%%%%%%

therefore I am wondering if this is something related to my laptop configuration or intrinsic to romanisim

thanks
sebastiano calchi novati

**Comment by schlafly** [comment]
Thanks Sebastiano.  I think the easiest thing for you to do would be to try the version we released yesterday (0.6.1) and see if the problem goes away.

For a little more background, it turns out that the romanisim _code_ is numpy 2 compatible, but they way that we built the binary wheels for release 0.5.2 that you get when you do "pip install romanisim" was not numpy 2 compatible.  So if for some reason you wanted to stick with 0.5.2 you could, but you would have to rebuild the binary yourself.  It's possible that something like
`pip install <package> --no-binary :all:`
would do that for you, but I haven't played around with that---the easiest option would be to use the release from yesterday, where I expect this to go away.  Let me know if that helps.

**Comment by qnov** [comment]
installed from scratch 0.6.1, problem solved - thanks!

**Comment by schlafly** [comment]
Perfect, thanks!
