### ISSUE TITLE
devdeps workflow failing

### ISSUE THREAD

**Issue by schlafly** [spacetelescope/romanisim#58]
The devdeps test workflow is failing on one architecture due to a dependency issue that doesn't really make sense to me.  Is there anything to do here or should we ignore?

https://github.com/spacetelescope/romanisim/actions/runs/5306499419

@zacharyburnett , tagging you in case the devdeps stuff makes more sense to you.  Feel free to declare WONTFIX.

**Comment by WilliamJamieson** [comment]
The issue is with: https://github.com/spacetelescope/romanisim/blob/a6a8ecd6964e1534ef6419b95eaa4868edb5f06a/tox.ini#L61

Doing this causes issues with the fact that `roman_datamodels` currently has a dependency on the `main` branch of RAD, it gets a bit circular and gives up.

I think dropping the `-U --upgrade-strategy eager` so that it is

```
devdeps: pip install -r requirements-dev.txt
```
Should resolve the problem.

**Comment by zacharyburnett** [comment]
I made a PR removing the `-U --upgrade-strategy eager`, but we should also remove the `main` branch dependency as PyPI will not accept that when built
